### ISSUE TITLE
The event passed as a parameter is not a valid wheel event, 'wheel' given.

### ISSUE THREAD

**Issue by Siregar** [autoNumeric/vue-autoNumeric#42]
**Description**
Using the wheel of a regular mouse or the up/down swipe gesture of a magic mouse throws an error in the dev tools.

**Implementation**
```
<VueAutonumeric
  :options="{
    allowDecimalPadding: 'floats',
    digitGroupSeparator: '.',
    decimalCharacter: ',',
    decimalPlaces: 2,
    decimalPlacesRawValue: 2,
    decimalCharacterAlternative: '.',
    currencySymbol: '\u00a0%',
    percentageEU2dec: true,
    currencySymbolPlacement: 's',
    roundingMethod: 'U',
    emptyInputBehavior: 'press',
  }"
/>
```

**How to reproduce**
1. Implement `<VueAutonumeric>` component
2. Click into the input
3. Scroll

![Bildschirmfoto 2020-05-15 um 09 43 07](https://user-images.githubusercontent.com/31287148/82024915-d61e7a00-9690-11ea-90fc-b493e37351d1.png)

**Comment by AlexandreBonneau** [comment]
Have you tried using AutoNumeric `v4.6.0`?
The wheel bug was fixed in that version (see https://github.com/autoNumeric/autoNumeric/issues/641)

**Comment by Siregar** [comment]
The error still occurs irregular when scrolling up and down. Tested with Magic Mouse and Trackpad. Scrolling left and right fires the error on every tick.

**Comment by marinastavares** [comment]
it's happening here as well 😢

**Comment by ArunAlex** [comment]
I am facing the same issue where if i swipe left/right on magic mouse I get above mentioned error. I was using autonumeric v4.5.4 and upgraded to 4.6 and still the same problem.

**Comment by JurgenStillaert** [comment]
We have the same problems with Apple Magic mouse v1.

**Comment by Siregar** [comment]
User Input already given; Any updates?

**Comment by psociety** [comment]
Yep, it still happens on 4.6.0
![Screenshot from 2022-08-23 08-41-28](https://user-images.githubusercontent.com/29523682/186088791-ba9c19d0-9a90-4003-bc81-5888d8412547.png)

![Screenshot from 2022-08-23 08-42-38](https://user-images.githubusercontent.com/29523682/186088819-9cea433b-96e5-45dc-af95-0ad1673bd434.png)

**Comment by codyjames** [comment]
Happening for me on 4.9.0.
